---
- name: "Load app variables"
  ansible.builtin.include_vars: app.vars.ansible.yaml

- name: "Install package dependencies"
  become: true
  ansible.builtin.apt:
    force: true
    name:
      - git

- name: "Obtain app from remote repository"
  become: true
  ansible.builtin.git:
    repo: http://192.168.56.1:8080/nsa-700/laravel-app.git
    dest: /var/www/app
    version: develop

- name: "Set permissions on application"
  become: true
  ansible.builtin.file:
    path: /var/www/app
    recurse: true
    owner: www-data
    group: www-data
    mode: "0777"

- name: "Update application .env"
  become: true
  ansible.builtin.template:
    src: files/laravel.env.j2
    dest: /var/www/app/.env
    owner: www-data
    group: www-data
    mode: "0777"

- name: "Update composer dependencies"
  become: true
  become_user: www-data
  community.general.composer:
    command: update
    working_dir: /var/www/app

- name: "Generate app encryption key"
  become: true
  become_user: www-data
  ansible.builtin.command:
    chdir: /var/www/app
    cmd: "php artisan key:generate"
  register: out
  changed_when: out.rc != 0

- name: "Clear artisan config"
  become: true
  become_user: www-data
  ansible.builtin.command:
    chdir: /var/www/app
    cmd: "php artisan config:clear"
  register: out
  changed_when: out.rc != 0

- name: "Cache artisan config"
  become: true
  become_user: www-data
  ansible.builtin.command:
    chdir: /var/www/app
    cmd: "php artisan config:cache"
  register: out
  changed_when: out.rc != 0

- name: "Migrate database"
  become: true
  become_user: www-data
  ansible.builtin.command:
    chdir: /var/www/app
    cmd: "php artisan migrate"
  register: out
  changed_when: out.rc != 0

- name: "Seed database"
  become: true
  become_user: www-data
  ansible.builtin.command:
    chdir: /var/www/app
    cmd: "php artisan db:seed"
  register: out
  changed_when: out.rc != 0
