---
- name: "Load app variables"
  ansible.builtin.include_vars: app.vars.ansible.yaml

- name: "Copy app to server"
  ansible.builtin.copy:
    src: files/app/
    dest: /var/www/app/
    directory_mode:
    owner: www-data
    group: www-data
    mode: "0644"

- name: "Update composer dependencies"
  community.general.composer:
    command: update
    working_dir: /var/www/app
  environment:
    COMPOSER_NO_INTERACTION: "1"
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: "Update application .env"
  ansible.builtin.template:
    src: files/laravel.env.j2
    dest: /var/www/app/.env
    owner: www-data
    group: www-data
    mode: "0644"

- name: "Generate app encryption key"
  ansible.builtin.command:
    chdir: /var/www/app
    cmd: "php artisan key:generate"
  register: out
  changed_when: out.rc != 0

- name: "Clear artisan cache"
  ansible.builtin.command:
    chdir: /var/www/app
    cmd: "php artisan config:cache"
  register: out
  changed_when: out.rc != 0
