- name: "Load nginx variables"
  ansible.builtin.include_vars: nginx.vars.ansible.yaml

- name: "Install nginx"
  ansible.builtin.apt:
    update_cache: true
    force: true
    package:
      - nginx

- name: "Update nginx configuration for php-fpm"
  ansible.builtin.copy:
    src: files/default.nginx
    dest: /etc/nginx/sites-available/default
    mode: "0755"

- name: "Validate nginx configuration"
  ansible.builtin.command:
    cmd: "nginx -t"
  register: out
  changed_when: out.rc != 0

- name: "Restart nginx with configuration updates"
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: "Add php test info file"
  ansible.builtin.copy:
    src: files/info.php
    dest: /var/www/html/
    mode: "0755"
