---
- name: "Load PHP variables"
  ansible.builtin.include_vars: php.vars.ansible.yaml

- name: "Install package dependencies"
  ansible.builtin.apt:
    update_cache: true
    force: true
    package:
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - lsb-release

- name: "Get PHP repository file"
  ansible.builtin.get_url:
    url: "https://packages.sury.org/php/README.txt"
    dest: "/tmp/README.txt"
    mode: "0755"

- name: "Move PHP repository file"
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/README.txt"
    dest: "/tmp/sury-php.sh"
    mode: "0755"

- name: "Add PHP repository file to trusted repositories"
  ansible.builtin.command:
    cmd: "/tmp/sury-php.sh"
  register: out
  changed_when: out.rc != 0

- name: "Install php and php modules"
  ansible.builtin.apt:
    update_cache: true
    force: true
    package:
      - php{{ php_version }}
      - php{{ php_version }}-cli
      - php{{ php_version }}-fpm
      - php{{ php_version }}-curl
      - php{{ php_version }}-bz2
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-intl
